### ISSUE TITLE
Using custom headers in request functions adds package user agent

### ISSUE THREAD

**Issue by Skullbite** [auguwu/orchid#173]
When using headers within the requesting functions an extra `user-agent` header gets inserted.

![image](https://user-images.githubusercontent.com/20869262/110026621-dc084900-7cfe-11eb-845b-9ed2e0375738.png)

**Comment by auguwu** [comment]
After some painful debugging, I got the result I wanted:

```js
// Request Headers
{
  'user-agent': 'owo my uwu?',
  authorization: 'ea sports its in the gay'
}
```

Only side-effect is mutating the `headers` value (defined [here](https://github.com/auguwu/orchid/blob/master/src/HttpClient.ts#L182-L195)) to do this correctly.
